### ISSUE TITLE
A bloated (?) list of recommended packages

### ISSUE THREAD

**Issue by wasowski** [rosin-project/rxros#2]
Right now the readme says that the following are useful addition:

```
sudo apt-get install git doxygen graphviz-* meld cmake
sudo apt-get install emacs qtcreator qt5-*
sudo apt-get install tree gimp
sudo apt-get install liburdfdom-tools
sudo apt-get install libcanberra-gtk-module
```

This list appears too long to me.  We should only list packages that are directly required or useful for rx_ros (including our tutorials, etc.).  It is not obvious to me that we need to install 
* doxygen (unless we have a doxygen documentation)
* graphviz (isn't this included by installing ROS tools for visualizing the node graph?)
* meld (why?)
* cmake (isn't this already installed with ROS as a dependency?)
* emacs (can't people use other editors?)
* gimp (for what would you use it?)
* tree (probably a too generic tool, people have various ways of exploring file systems).

Others are also not super clearly needed.  Feel free to revise this in the README or just respond here and I can revise.

**Comment by gavanderhoorn** [comment]
Additionally: as we're aiming for integration in the regular ROS workflow, any really required packages should be listed as `build` and/or `exec` dependencies of the `rx_ros` package (in the `package.xml`).

That way they will be automatically installed when running `rosdep`.

**Comment by wasowski** [comment]
I am aiming for that, this issue is there to understand what is needed.

**Comment by henrik7264** [comment]
They are not needed at all. They are just some packages I have been happy to use during my work with building the robot. I shall remove the from the README.md file.

**Comment by henrik7264** [comment]
The section ha been removed from the README.md file
