### ISSUE TITLE
README.md should explain how to use observable::from_transform and operator::send_transform

### ISSUE THREAD

**Issue by henrik7264** [rosin-project/rxros#26]
The special include statement #include <rxros_tf.h> should be explained in the README.md file

**Comment by gavanderhoorn** [comment]
I'll leave this one to you @henrik7264. I've merely changed some file locations and package names.

Suggestion: in your explanation, refer the reader to how the situation is analogous to `roscpp` and `tf`: `tf` has a set of additional packages that add functionality specific to a certain topic or functional context (ie: packages for converting to-and-from certain math libraries, working with geometric data (points, poses, etc).

That is not included in the base package, but in an extension. Similar to how `rxros` and `rxros_tf` are set up.

**Comment by gavanderhoorn** [comment]
Should be fixed by #34.
