### ISSUE TITLE
What's in the future?

### ISSUE THREAD

**Issue by PhotoTeeborChoka** [rosin-project/rxros#38]
This is an amazing library, but has an unclear future. Can you shed some light into the project's future? It's been almost a year since the last merge.

**Comment by henrik7264** [comment]
Hi,

We have now for some time worked on a ROS2 version of the library. It will soon be open for public access with support for both C++ and Python. I also hope we soon will be able to to update the ROS1 version. 

Take a look at https://github.com/rosin-project/rxros2. It will soon be opened.

Spread the word. We need people to both use and maintain the library.

**Comment by PhotoTeeborChoka** [comment]
Thanks for the information, amazing work, amazing progress! Keep up the good work.

Please, do bump up this issue, when the `rxros2` is public... many of us are eagerly awaiting it!

Thanks!

**Comment by henrik7264** [comment]
Hi PhotoTeeborChoka,

Thanks a lot for all the positive words. It warms a lot and you don't know how happy it make us all.

I shall let you know when RxROS2 is ready for public use.

Kindly Regards Henrik

**Comment by gavanderhoorn** [comment]
We've just made [rosin-project/rxros2](https://github.com/rosin-project/rxros2) public.

There are some rough edges, but it *should* be usable.

Related repository: [rosin-project/rxros2_benchmarks](https://github.com/rosin-project/rxros2_benchmarks).

**Comment by gavanderhoorn** [comment]
I'm going to close this, so we can keep the issue tracker for dealing with actual issues.

Thanks for your interest @PhotoTeeborChoka, we're a bit busy with a submission right now, but perhaps we can shift focus to address some of the outstanding issues in `rxros` after that.
