### ISSUE TITLE
Clarify status of support for other OS versions

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/rxros#6]
The readme seems to imply that Ubuntu Bionic is required, but it doesn't say anything about Xenial.

It would be good to be specific about which version of Ubuntu (or other OS) are supported, and which are not.

**Comment by gavanderhoorn** [comment]
I'm on Xenial, and I must add the following to the various `CMakeLists.txt` to get things to compile:

```cmake
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif()
```

The `brickpi` package won't compile for me though, even with this.

I get a huge wall-of-text, ending with:

```
/home/user/rxros_ws/src/rx_ros/examples/brickpi3/src/BrickPi3Ros_rx.cpp:155:15:   required from here
/home/user/rxros_ws/src/rx_ros/examples/brickpi3/src/BrickPi3Observable_rx.h:195:44: internal compiler error: in tsubst_copy, at cp/pt.c:13039
                 const uint8_t id = port2id(port);
                                            ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
```
this is with the standard GCC 5.4.0, so it may be too old.

**Comment by gavanderhoorn** [comment]
We now explicitly require C++14 support for the examples (rosin-project/rxros_examples#1).

Not sure whether we should export it as a definition from `rxros`.

**Comment by wasowski** [comment]
> Not sure whether we should export it as a definition from `rxros`.

Isn't this one of the last issues that is holding back https://github.com/rosin-project/rxros_examples/pull/6 ?

**Comment by gavanderhoorn** [comment]
I believe we could actually close this issue, as the readme now *does* state what the compatibility with Xenial and Bionic is (although it's left somewhat implied by only mentioning ROS Kinetic and Melodic, but that is on purpose).

> Isn't this one of the last issues that is holding back [rosin-project/rxros_examples#6](https://github.com/rosin-project/rxros_examples/pull/6) ?

It's probably something to consider for that one as well yes.

**Comment by gavanderhoorn** [comment]
I'll actually close this as the readme has been updated in #34.
