### ISSUE TITLE
Move brick3 example to a separate repository rx_ros_examples

### ISSUE THREAD

**Issue by wasowski** [rosin-project/rxros#9]
See #3

**Comment by gavanderhoorn** [comment]
@henrik7264: let me know if you'd agree with this. I can create the repository.

**Comment by gavanderhoorn** [comment]
Created: [rosin-project/rxros_examples](https://github.com/rosin-project/rxros_examples).

**Comment by gavanderhoorn** [comment]
Implemented in #14.

and rosin-project/rxros_examples#1.

**Comment by gavanderhoorn** [comment]
Fixed in #14 and rosin-project/rxros_examples#1.
